### ISSUE TITLE
(Bug) Cat interference 

### ISSUE THREAD

**Issue by forever-and-a-day** [Aniiiiiiiiiiiiiiiiiimal/QuickMenuVolume#3]
When the volume  menu is visible, the VRChat plus cat's speech bubble is covered up. Could you either move the cat a lil further to the right or move the volume menu a lil higher up? 
Thanks! ^-^

**Comment by ItzOnlyAnimal** [comment]
Try the latest hotfix I just published
I wasn't able to test this much as I dont have VRC+ at the moment, but it should move further to the right like the cat does.
Let me know of any other issues, I'm currently working on a rewrite of this mod to fix most current issues I know of :P
